management:
    context-path: /internal

synapse:
  consumer-process:
    enabled: true

exampleservice:
  product-channel: example-products
  banana-channel: example-bananas

logging:
    config: classpath:logback-console.xml

server:
  port: 5555